Add 'both' subcommand and xclip_double_output().

diff --git a/upm b/upm
--- a/upm
+++ b/upm
@@ -10,7 +10,7 @@ usage ()
 {
     cat << EOF >&2
 Usage:
-    $(basename $0) [-o | -c] [-p] [<key> | pass <key> | user <key> | ls]
+    $(basename $0) [-o | -c] [-p] [<key> | pass <key> | user <key> | both <key> | ls]
 
 An ultra-minimalistic password manager.
 
@@ -18,6 +18,8 @@ Commands:
     pass <key>  (Default) Get password corresponding to the key.
                 If just the key is given, this is the default.
     user <key>  Get the username corresponding to the key.
+    both <key>  Get the username and password, separated by a newline
+                corresponding to the key.
     ls          List all keys in vault. Outputs to stdout.
 
 Options:
@@ -134,6 +136,60 @@ get_user ()
     return ${PIPESTATUS[1]}
 }
 
+
+# Exit codes:
+#   0: username and password from 3 line record
+#   1: empty username, password from 2 line record
+#   2: username and password from record with >3 lines
+#   3: record found, but no username or password (1 line record)
+#   4: record not found
+get_both ()
+{
+    local PWKEY
+    PWKEY="$1"
+    cleanup | sed -n -E "
+        1 b blanks          # handle first line
+        $ q 4               # handle end of file
+        /^\S+/ d
+        :blanks
+        /^\s*$/ {
+            :eatws
+            n
+            /^\s*$/ b eatws
+            b match
+            }
+        : match
+        /^${PWKEY}/ {
+            $ q 3
+            n
+            h
+            /^\s*$/ q 3         # empty line after key
+            n
+            /^\s*$/ b nouser    # empty 2nd line after key
+            H
+            n
+            /^\s*$/ b output    # two non-empty lines after key = ok
+            /^.+/ b malformed   # more than three non-empty non-comment lines
+            :output
+            x
+            p
+            q 0
+            :malformed          # malformed record, output but change exit code
+            x
+            p
+            q 2
+            :nouser             # No user in record, output empty line + pw
+            s/^.*$//            # Clear pattern space
+            p
+            x
+            p
+            q 1
+        }
+        $ q 3" | tr '\n' '\r' | sed 's/\r$//' | tr '\r' '\n'
+    return ${PIPESTATUS[1]}
+}
+
+
 # List lines with preceding empty (or only whitespace containing) lines
 # and at least one consecutive non-empty line.
 list_keys ()
@@ -173,6 +229,25 @@ xclip_output ()
 }
 
 
+xclip_double_output ()
+{
+    local CLEARTIME INP UNAME PASSW
+    CLEARTIME=30
+
+    INP="$(cat | tr '\n' '\r')"
+    UNAME=$(echo "$INP" | sed -n 's/^\([^\r]*\)\r.*$/\1/p')
+    PASSW=$(echo "$INP" | sed -n 's/^[^\r]*\r\([^\r]*\)\r*$/\1/p')
+
+    ( echo -n "$UNAME" | xclip -i -quiet -loops 1 2> /dev/null \
+        && echo -n "$PASSW" | xclip -i -loops 1 2> /dev/null ) & \
+        disown
+    ( sleep $CLEARTIME ; \
+        xclip -o 2>&1 > /dev/null \
+        xclip -o 2>&1 > /dev/null ) & \
+        disown
+}
+
+
 [ $# -le 4 ] && [ $# -ge 1 ] || usage 1 "Error: Wrong number of arguments"
 [ -z "$UPMFILE" ] && [ -r "$CONFFILE" ] && source "$CONFFILE"
 [ -f "$UPMFILE" ] || die 1 "Vault file '${UPMFILE}' not found."
@@ -189,6 +264,8 @@ while [ $# -gt 0 ] ; do
             ACTION=get_password ;;
         user) # get username
             ACTION=get_user ;;
+        both) # get both user and password
+            ACTION=get_both ;;
         ls) # list keys
             ACTION=list_keys
             OUTPUT=cat ;;
@@ -218,6 +295,10 @@ done
 [ "$OUTPUT" = "xclip_output" ] && ! xclip -h &> /dev/null \
     && die 1 "$(basename $0) requires xclip for clipboard output."
 
+if [ "$ACTION" = "get_both" ] && [ $OUTPUT = "xclip_output" ]; then
+    OUTPUT="xclip_double_output"
+fi
+
 [ -n "$PASSPHRASE_ARGS" ] && echo -n "Enter vault passphrase: " >&2
 [ -t 0 ] && stty -echo
 gpg -d ${PASSPHRASE_ARGS} ${UPMFILE} 2> /dev/null \
@@ -230,6 +311,7 @@ PIPE_EXITS=("${PIPESTATUS[@]}")
 
 # check GPG exit status
 [ ${PIPE_EXITS[0]} -ne 0 ] && die 5 "gpg: decrypt failed."
+
 # check action exit status
 if [ ${PIPE_EXITS[1]} -eq 0 ] ; then
     [ "$ACTION" = "get_password" ] \
@@ -240,8 +322,9 @@ fi
 [ ${PIPE_EXITS[1]} -eq 2 ] \
     && echo "Warning: Extra lines in record for key '$KEY'" >&2
 [ ${PIPE_EXITS[1]} -eq 3 ] && die 5 "key '$KEY' not found"
+[ ${PIPE_EXITS[1]} -eq 4 ] && echo "Warning: Extra lines in record for key '$KEY'" >&2
 
-if [ "$OUTPUT" = "xclip_output" ] ; then
+if [ "$OUTPUT" = "xclip_output" ] || [ "$OUTPUT" = "xclip_double_output" ]; then
     echo "Output sent to clipboard." >&2
 elif [ "$OUTPUT" = "cat" ] && [ "$ACTION" != "list_keys" ]; then
     # Output newline for compatibility with msmtp etc.
